### ISSUE TITLE
i may be late but why does this happen?

### ISSUE THREAD

**Issue by thewsmred** [Alienmario/customguns-hl2dm#3]
when i use sm_customgun i get this message
] sm_customgun weapon_shovel
Sorry, you need to be in-game to spawn guns at your origin
any answers?

**Comment by thewsmred** [comment]
i forgot to mention this but i am in-game

**Comment by Alienmario** [comment]
This will happen if you run a listen server (which is unsupported by SM). Run a proper dedicated one.

**Comment by thewsmred** [comment]
i wasnt expecting an answer because of how old this github is, this worked as it should, thanks

**Comment by thewsmred** [comment]
i wasnt expecting an answer because of how old this github is, this worked as it should, thanks
